### ISSUE TITLE
Center content of textbox

### ISSUE THREAD

**Issue by redseujac75** [Dirkster99/NumericUpDownLib#22]
I'd like to center the content of the textbox. Now it's always aligned to the right.
When I use `HorizontalContentAlignment="Center"` it doesn't work. 
Am I missing something?

**Comment by heartacker** [comment]
![image](https://user-images.githubusercontent.com/1876302/176993789-c6b6af33-d5de-4290-a8e5-1ed74c41c18b.png)
![image](https://user-images.githubusercontent.com/1876302/176993792-63d6e70d-2131-44a0-b41c-2508f2c7f545.png)

![image](https://user-images.githubusercontent.com/1876302/176993797-c34b4613-6ee8-4e82-9839-07921db69522.png)

#41

**Comment by redseujac75** [comment]
OK. Master and NuGet should be updated. Is it possible to let me know when version 3.0 will be updated? Thanks.

**Comment by Dirkster99** [comment]
@redseujac75 Master is updated - please test and let us know if you find a problem

**Comment by redseujac75** [comment]
Master is still version 3.0.0.0.
Do not see and update. Sorry if I am wrong.
For my project I'm using Visual Studio 2022 and NumericUpDownLib is installed through Nuget Package Manager.
Could you please update your package in Nuget so I'm able to apply/update it in my project?

**Comment by redseujac75** [comment]
OK. Although the version is still 3.0.0.0, I have downloaded, installed and ran the Master in Visual Studio 2022. Then I referenced the new built .NET 4 NumericUpDownLib.dll file in my project. It's working now properly and now the content of the textbox is aligned to left/center/right according to the settings in `HorizontalContentAlignment` property. Thank you for the fix.

**Comment by Dirkster99** [comment]
@redseujac75 Version 3.1 is out now.

**Comment by redseujac75** [comment]
@Dirkster99 

Thank you very much 👍
