### ISSUE TITLE
Option to display more decimal points

### ISSUE THREAD

**Issue by eimear15** [Dirkster99/NumericUpDownLib#35]
Hi I am using DoubleUpDown and would like to display more decimal points, i.e. 0.0001 instead of the default 0.01. Is there an easy way to do this that I am missing? I've tried changing the DisplayLength, the StepSize, the NumberStyle but I still have only the 2 decimal places. Thanks!

**Comment by eimear15** [comment]
@Dirkster99 could you help with this?

**Comment by heartacker** [comment]
try `FormatString`

**Comment by eimear15** [comment]
@heartacker thanks that fixes it!
