### ISSUE TITLE
Is it possible supporting Command Binding for ValueChanged Event?

### ISSUE THREAD

**Issue by heartacker** [Dirkster99/NumericUpDownLib#40]
now we have to use `ValueChanged="UIntegerUpDown_ValueChanged"`
can we use binding Command for this event?

**Comment by heartacker** [comment]
@Dirkster99 I am unable to dev the complicated feature, But I need this indeed for my MVVM.

Could you please help me. Thanks a lot

**Comment by Dirkster99** [comment]
I guess this was about the Cntrl+Enter force trigger value changed event, right? If so, can we close this? If not, please explain more detailed what you are trying to accomplish and why.

I am not sure if I can help with this Command binding but maybe someone else in the community can help once its clearer what you are trying to solve. thanx

**Comment by heartacker** [comment]
https://stackoverflow.com/questions/16059390/what-is-the-difference-between-wpf-command-and-event-in-wpf
