### ISSUE TITLE
IsEnableValidatingIndicator missing

### ISSUE THREAD

**Issue by JKriegerInno** [Dirkster99/NumericUpDownLib#45]
Looks like the **IsEnableValidatingIndicator** flag, mentioned in the [change log for 3.1](https://github.com/Dirkster99/NumericUpDownLib#features-added-in-version-31), did not make it into the release. Is this intended?

![image](https://user-images.githubusercontent.com/63112587/180219633-29193849-5412-4eaf-999a-078aa88951ab.png)

**Comment by heartacker** [comment]
use `EnableValidatingIndicator`

**Comment by JKriegerInno** [comment]
Thanks that did it.
