### ISSUE TITLE
xaml Binding error with new version

### ISSUE THREAD

**Issue by ClourneySemi** [Dirkster99/NumericUpDownLib#52]
System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property. Double:'NaN' BindingExpression:Path=Width; DataItem='TextBox' (Name='PART_Measuring_Element'); target element is 'TextBox' (Name=''); target property is 'MaxWidth' (type 'Double')

**Comment by comeero** [comment]
Same issues here

**Comment by heartacker** [comment]
@Dirkster99 could you please help to fix this
thanks
![image](https://user-images.githubusercontent.com/1876302/203318305-618ca485-85c8-45b0-a231-97c059310c23.png)

**Comment by heartacker** [comment]
@Dirkster99 I have reverted the pr in #54
This reverts commit 8f28c35e8a6e93fcaab04801ae959b9de681b22b, reversing
changes made to b8a49603a4f20254fd1db13e73511a3853042952.

**Comment by heartacker** [comment]
this bug is fixed

**Comment by ClourneySemi** [comment]
❤️
