### ISSUE TITLE
Is it possible to make a WinUI 3 controls

### ISSUE THREAD

**Issue by heartacker** [Dirkster99/NumericUpDownLib#57]
need this in WinUI 3
![image](https://user-images.githubusercontent.com/1876302/226161323-da8093c9-4c2e-4135-b003-143599ba4b00.png)

**Comment by Dirkster99** [comment]
I am not sure about this one. I freshly installed Visual Studio 2022 Community Edition and got WinUI installed as well. Then I tried to develop a solution with a Control Library but I could not even get the [AbstractBaseUpDown.cs](https://github.com/Dirkster99/NumericUpDownLib/blob/0dd9bd8e569736f0192107cfaadd340a7e0aa90e/source/NumericUpDownLib/Base/AbstractBaseUpDown.cs#L1) class to compile. The Visual Studio 2022 kept changing the using statements and I tried to Reference `System.Windows.Input` (and other WPF libraries) as shown below but the thing just kept complaining...

It seems to me that WPF and WinUI 3 are not compatible and so we are looking at a development from scratch and no simple port, right?

![image](https://user-images.githubusercontent.com/2129700/227619306-ca3d1412-7377-4799-a0f1-958294383f9c.png)
