### ISSUE TITLE
[Request]  please add IsMouseDragHorizontal bool

### ISSUE THREAD

**Issue by sirfnomi** [Dirkster99/NumericUpDownLib#7]
please add IsMouseDragHorizontal bool
sometimes horizontal increment is disturbing work

thanks for your work :)

**Comment by Dirkster99** [comment]
Hi,

I am not sure how you want this to work - so could you tell me more about your requirements?

You want to add a flag called: **IsMouseDragHorizontal**, right? And then when it is set to **true**:
**IsMouseDragHorizontal** = true;

you want to allow only vertical movements for increment and decrement. Is that how it should work for you?

**Comment by sirfnomi** [comment]
> you want to allow only vertical movements for increment and decrement. Is that how it should work for you?

yes, i actually want to only use vertical movements for increment and decrement . i'll be very easy if we can get movement flags like Vertical Only , Horizontal Only and VerticalHorizontalBoth

also can we set it to default that after editing text press enter will set the value of control

**Comment by Dirkster99** [comment]
Sorry for the late response but I finally got time to [implement your request](https://github.com/Dirkster99/NumericUpDownLib/wiki#canmousedrag). Please let me know what you think about it.

Cheers Drk
