### ISSUE TITLE
When setting a value in xaml (binding or manual), increase no longer works.

### ISSUE THREAD

**Issue by RiotNOR** [Dirkster99/NumericUpDownLib#8]
For some reason whenever I set a value either by binding or manually typing it in it is no longer possible to increase the value. It's as if the spinner believes the value is also MaxValue.

**EDIT** This seems to only be happening when inside a ListView datatemplate. I cannot replicate this outside of it. This happens regardless if MaxValue is set or not (if maxvalue is not set outside of a listview the same thing happens)

**Comment by Dirkster99** [comment]
I can replicate the issue with the `ByteUpDown` control in the demo application. The control value cannot be increased beyond 5 for whatever reason :-(  It seems to be a weird timing problem or such because I am pretty sure I tested this before ...maybe different instances of the control share something which leads to this error? I am not sure at the moment

**Comment by RiotNOR** [comment]
```
<ListView
                Name="lvTest"
                HorizontalAlignment="Stretch"
                VerticalAlignment="Stretch">
                <ListView.ItemTemplate>
                    <DataTemplate>
                        <num:NumericUpDown MaxValue="123" Value="2" />
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>
```

Then just adding a single item (lvTest.Items.Add(1);). Debugging the coerce functions sees it run into CoerceValue and set maxvalue as value. It's as if max value never gets set while in a listview.

**Comment by Dirkster99** [comment]
That's a strange fix.

It's breaking the unit test - meaning there is a sequence of value changes (eg.: Min. Value, Max) that will leave an invalid range (eg.: Value > Max).

Your fix makes the `ByteUpDown` work in the demo. But its initially set to Min=0,Value=5,Max=128 and it displays an initial Value=0 and jumps to 6 on 1 up click :-(

So, its not only breaking the unit test but also other things… my guess is that control instances share a value (maybe through one of the base classes and thus this weird error (which is not always stable) occurs)... or something along these lines is happening...?

**Comment by Dirkster99** [comment]
I found a different fix that works for me:
https://github.com/Dirkster99/NumericUpDownLib/tree/Fix_Issue_8

...without breaking the unit test and it does not seem to cause any new issues in the demo as far as I can see :-)

Would you be able to test whether this would also work for your ListView test case? If not, could you give me a minimal sample to better understand what you are looking at?

Thanx Drk

**Comment by RiotNOR** [comment]
That seemed to have cleared it up nicely. NumericUpDown now works fine in a ListView.

**Comment by Dirkster99** [comment]
Cool - I'll think of a few more unit tests and probably do the next release this weekend .-)

Thanks for the detailed feedback and quick responses.
